---
version: 2

log-file: /tmp/efm.log
log-level: 1

root-markers:
  - .git/
  - .git

tools:
  # linters

  eslint-lint: &eslint-lint
    lint-source: eslint
    lint-command: "./node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  hadolint-lint: &hadolint-lint
    lint-source: hadolint
    lint-command: "hadolint"
    lint-formats:
      - "%f:%l %m"

  jsonlint-lint: &jsonlint-lint
    lint-source: jsonlint
    lint-command: "jsonlint -c"
    lint-stdin: true
    lint-formats:
      - "line %l, col %c, found: %m"

  markdownlint-lint: &markdownlint-lint
    lint-source: markdownlint
    lint-command: "markdownlint --stdin"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c MD%n/%*[^ ] %m"
      - "%f:%l MD%n/%*[^ ] %m"

  shellcheck-lint: &shellcheck-lint
    lint-source: shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %t%*[^:]: %m [SC%n]"

  yamllint-lint: &yamllint-lint
    lint-source: yamllint
    lint-command: "yamllint --strict --format parsable ${INPUT}"
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: [%t%*[a-z]] %m"
    env:
      - "PYTHONIOENCODING=UTF-8"

  vale-lint: &vale-lint
    lint-source: vale
    lint-command: "vale --relative --output line ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c:%*[^:]:%m"

  # formatters

  fixjson-format: &fixjson-format
    format-command: "fixjson"
    format-stdin: true

  prettier-format: &prettier-format
    format-command: "prettier --stdin-filepath ${INPUT} --single-quote"
    format-stdin: true

  shellharden-format: &shellharden-format
    format-command: "shellharden --transform ''"
    format-stdin: true

  shfmt-format: &shfmt-format
    format-command: "shfmt -ln bash -i 2 -bn -ci -sr -kp"
    format-stdin: true

  stylua-format: &stylua-format
    format-command: "stylua --search-parent-directories --stdin-filepath ${FILENAME} -"
    format-stdin: true

languages:
  css:
    - <<: *eslint-lint
    - <<: *prettier-format

  dockerfile:
    - <<: *hadolint-lint

  html:
    - <<: *eslint-lint
    - <<: *prettier-format

  javascript:
    - <<: *eslint-lint
    - <<: *prettier-format

  javascriptreact:
    - <<: *eslint-lint
    - <<: *prettier-format

  json:
    - <<: *jsonlint-lint
    - <<: *fixjson-format

  less:
    - <<: *eslint-lint
    - <<: *prettier-format

  lua:
    - <<: *stylua-format

  markdown:
    - <<: *markdownlint-lint
    - <<: *vale-lint
    - <<: *prettier-format

  sass:
    - <<: *eslint-lint
    - <<: *prettier-format

  scss:
    - <<: *eslint-lint
    - <<: *prettier-format

  sh:
    - <<: *shellcheck-lint
    - <<: *shellharden-format

  text:
    - <<: *vale-lint

  typescript:
    - <<: *eslint-lint
    - <<: *prettier-format

  typescriptreact:
    - <<: *eslint-lint
    - <<: *prettier-format

  yaml:
    - <<: *yamllint-lint
