# updated system packages
brew "bash"
brew "git"
brew "grep"
brew "ruby"
brew "vim"
brew "zsh"

# linters
brew "alexjs"
brew "hadolint"
brew "languagetool"
brew "proselint"
brew "shellcheck"
brew "write-good"
brew "yamllint"

# extra packages
brew "coreutils"
brew "fasd"
brew "fd"
brew "fzf"
brew "gnupg"
brew "htop"
brew "jq"
brew "lsd"
brew "neovim"
brew "railwaycat/emacsmacport/emacs-mac"
brew "ripgrep"
brew "schniz/tap/fnm"
brew "starship"
brew "tmux"
brew "tree"
brew "zplug"

# casks
cask "alacritty"
cask "alfred"
cask "docker"
cask "gimp"
cask "homebrew/cask-fonts/font-iosevka"
cask "homebrew/cask-fonts/font-iosevka-nerd-font"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "rectangle"
