# https://docs.helix-editor.com/configuration.html

theme = "catppuccin_macchiato"

[editor]
cursorline = true
auto-save = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.insert]
A-b = ["move_prev_word_start", "move_char_left"]
A-f = ["move_next_word_end", "move_char_right"]
C-b = "move_char_left"
C-f = "move_char_right"
