source "$HOME/.dotfiles/zsh/base.zsh"
source "$HOME/.dotfiles/zsh/functions.zsh"
source "$HOME/.dotfiles/zsh/plugins.zsh"

[ -s "$HOME/.zshrc.local.zsh" ] && source "$HOME/.zshrc.local.zsh"

dircolors=$(dircolors >/dev/null 2>&1 && echo 'dircolors' || echo 'gdircolors')
eval $($dircolors -b $HOME/.LS_COLORS/LS_COLORS)
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"

source_if_exists "$HOME/.config/base16-shell/scripts/base16-tomorrow-night.sh"

source_if_exists "$HOME/.fzf.zsh"
export FZF_DEFAULT_COMMAND='(git ls-tree -r --name-only HEAD || ag -g '') 2> /dev/null'

source_if_exists "$HOME/.rvm/scripts/rvm"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

source_if_exists "$HOME/.sdkman/bin/sdkman-init.sh"

source_if_exists "$HOME/.nvm/nvm.sh"
